name: Go
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.25"
          - "1.26"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Build & Test
        run: |
          go mod download
          go test -race -v ./...
